/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrar;

import proyectofinal.*;
import Control.*;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author josephjoestar
 */
public class AdministrarAula extends javax.swing.JFrame {
    
    validar val = new validar();
    connection conn = new connection();   
    String id;
    boolean aux = false;
    /**
     * Creates new form AdminsitrarDirectores
     */
    public AdministrarAula() {
        initComponents();
        this.setLocationRelativeTo(null);
        agregarAu_pan.setVisible(false);
        agregarCa_pan.setVisible(false);
        agregarEq_pan.setVisible(false);
        modificarAu_pan.setVisible(false);
        ae_pan.setVisible(false);
        consultar(aulas_tab,"SELECT * FROM aulas");
        obtenerCategorias();        
        UIManager.put("OptionPane.background", Color.WHITE);
        UIManager.getLookAndFeelDefaults().put("Panel.background", Color.WHITE);
        
        validar val = new validar();
        LAB_nom.setText(val.tipoUsuario());
        if(SharedData.getTipoUsuario().equals("Profesor")){
            BTN_maestros.setEnabled(false);
            BTN_carreras.setEnabled(false);
            BTN_planes.setEnabled(false);
            BTN_aulas.setEnabled(false);
            BTN_horario.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        agregarCa_pan = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cnombre_txt = new javax.swing.JTextField();
        cguardar_bot = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cdescripcion_txt = new javax.swing.JTextArea();
        ccancelar_bot = new javax.swing.JButton();
        agregarEq_pan = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        enombre_txt = new javax.swing.JTextField();
        eguardar_bot1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        ecategoria_cb1 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        edescripcion_txt = new javax.swing.JTextArea();
        ecancelar_bot1 = new javax.swing.JButton();
        agregarAu_pan = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        aclave_txt = new javax.swing.JTextField();
        anombre_txt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        aguardar_bot = new javax.swing.JButton();
        atipo_cb = new javax.swing.JComboBox<>();
        acapacidad_sp = new javax.swing.JSpinner();
        acancelar_bot = new javax.swing.JButton();
        modificarAu_pan = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        mnombre_txt = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        mguardar_bot = new javax.swing.JButton();
        mtipo_cb = new javax.swing.JComboBox<>();
        mcapacidad_sp = new javax.swing.JSpinner();
        mcancelar_bot = new javax.swing.JButton();
        ae_pan = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        aeguardar_bot = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        ae_tab = new javax.swing.JTable();
        aecancelar_bot = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aulas_tab = new javax.swing.JTable();
        aasignar_bot = new javax.swing.JButton();
        agregarAu_bot = new javax.swing.JButton();
        agregarCa_bot = new javax.swing.JButton();
        agregarEq_bot = new javax.swing.JButton();
        amodificar_bot = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LAB_nom = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BTN_menu = new javax.swing.JButton();
        BTN_disponibilidad = new javax.swing.JButton();
        BTN_maestros = new javax.swing.JButton();
        BTN_materias = new javax.swing.JButton();
        BTN_carreras = new javax.swing.JButton();
        BTN_planes = new javax.swing.JButton();
        BTN_aulas = new javax.swing.JButton();
        BTN_grupo = new javax.swing.JButton();
        BTN_horario = new javax.swing.JButton();
        BTN_puntos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarCa_pan.setBackground(new java.awt.Color(255, 255, 255));
        agregarCa_pan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.darkGray));
        agregarCa_pan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Nombre:");
        agregarCa_pan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Descripción:");
        agregarCa_pan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, 20));

        cnombre_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cnombre_txtKeyTyped(evt);
            }
        });
        agregarCa_pan.add(cnombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 218, -1));

        cguardar_bot.setText("Guardar");
        cguardar_bot.setToolTipText("");
        cguardar_bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cguardar_botActionPerformed(evt);
            }
        });
        agregarCa_pan.add(cguardar_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 105, -1));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel13.setText("Agregar Categoría");
        agregarCa_pan.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        cdescripcion_txt.setColumns(20);
        cdescripcion_txt.setRows(5);
        jScrollPane3.setViewportView(cdescripcion_txt);

        agregarCa_pan.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 340, 140));

        ccancelar_bot.setText("Cancelar");
        ccancelar_bot.setToolTipText("");
        ccancelar_bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccancelar_botActionPerformed(evt);
            }
        });
        agregarCa_pan.add(ccancelar_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 105, -1));

        jPanel3.add(agregarCa_pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 490, 380));

        agregarEq_pan.setBackground(new java.awt.Color(254, 254, 254));
        agregarEq_pan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.darkGray));
        agregarEq_pan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Nombre:");
        agregarEq_pan.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Descripción:");
        agregarEq_pan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Categoria:");
        agregarEq_pan.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, 20));

        enombre_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                enombre_txtKeyTyped(evt);
            }
        });
        agregarEq_pan.add(enombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 218, -1));

        eguardar_bot1.setText("Guardar");
        eguardar_bot1.setToolTipText("");
        eguardar_bot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eguardar_bot1ActionPerformed(evt);
            }
        });
        agregarEq_pan.add(eguardar_bot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 105, -1));

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel16.setText("Agregar Equipo");
        agregarEq_pan.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        ecategoria_cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aula", "Laboratorio" }));
        agregarEq_pan.add(ecategoria_cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 220, -1));

        edescripcion_txt.setColumns(20);
        edescripcion_txt.setRows(5);
        jScrollPane4.setViewportView(edescripcion_txt);

        agregarEq_pan.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 340, -1));

        ecancelar_bot1.setText("Cancelar");
        ecancelar_bot1.setToolTipText("");
        ecancelar_bot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecancelar_bot1ActionPerformed(evt);
            }
        });
        agregarEq_pan.add(ecancelar_bot1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 105, -1));

        jPanel3.add(agregarEq_pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 490, 380));

        agregarAu_pan.setBackground(new java.awt.Color(254, 254, 254));
        agregarAu_pan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.darkGray));
        agregarAu_pan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Clave:");
        agregarAu_pan.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Nombre:");
        agregarAu_pan.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Tipo:");
        agregarAu_pan.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, 20));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Capacidad:");
        agregarAu_pan.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, 20));
        agregarAu_pan.add(aclave_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 218, -1));

        anombre_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anombre_txtKeyTyped(evt);
            }
        });
        agregarAu_pan.add(anombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 218, -1));

        jLabel25.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel25.setText("Agregar Aula");
        agregarAu_pan.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        aguardar_bot.setText("Guardar");
        aguardar_bot.setToolTipText("");
        aguardar_bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aguardar_botActionPerformed(evt);
            }
        });
        agregarAu_pan.add(aguardar_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 105, -1));

        atipo_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aula", "Laboratorio" }));
        agregarAu_pan.add(atipo_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 220, -1));
        agregarAu_pan.add(acapacidad_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 220, -1));

        acancelar_bot.setText("Cancelar");
        acancelar_bot.setToolTipText("");
        acancelar_bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acancelar_botActionPerformed(evt);
            }
        });
        agregarAu_pan.add(acancelar_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 105, -1));

        jPanel3.add(agregarAu_pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 490, 380));

        modificarAu_pan.setBackground(new java.awt.Color(255, 255, 255));
        modificarAu_pan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.gray, java.awt.Color.darkGray));
        modificarAu_pan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Nombre:");
        modificarAu_pan.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Tipo:");
        modificarAu_pan.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, 20));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Capacidad:");
        modificarAu_pan.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, 20));

        mnombre_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mnombre_txtKeyTyped(evt);
            }
        });
        modificarAu_pan.add(mnombre_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 218, -1));

        jLabel30.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel30.setText("Modificar Aula");
        modificarAu_pan.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        mguardar_bot.setText("Guardar");
        mguardar_bot.setToolTipText("");
        mguardar_bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mguardar_botActionPerformed(evt);
            }
        });
        modificarAu_pan.add(mguardar_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 105, -1));

        mtipo_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aula", "Laboratorio" }));
        modificarAu_pan.add(mtipo_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 220, -1));
        modificarAu_pan.add(mcapacidad_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 220, -1));

        mcancelar_bot.setText("Cancelar");
        mcancelar_bot.setToolTipText("");
        mcancelar_bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcancelar_botActionPerformed(evt);
            }
        });
        modificarAu_pan.add(mcancelar_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 105, -1));

        jPanel3.add(modificarAu_pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 490, 380));

        ae_pan.setBackground(new java.awt.Color(254, 254, 254));
        ae_pan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ae_pan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel12.setText("Asignar Equipo");
        ae_pan.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        aeguardar_bot.setText("Guardar");
        aeguardar_bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aeguardar_botActionPerformed(evt);
            }
        });
        ae_pan.add(aeguardar_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 110, 40));
        ae_pan.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 710, 10));

        ae_tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoría", "ID", "Equipo", "Descripción", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ae_tab);

        ae_pan.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 780, 360));

        aecancelar_bot.setText("Cancelar");
        aecancelar_bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aecancelar_botActionPerformed(evt);
            }
        });
        ae_pan.add(aecancelar_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 110, 40));

        jPanel3.add(ae_pan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 610));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel10.setText("Aulas");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        aulas_tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Clave", "Nombre", "Tipo", "Capacidad"
            }
        ));
        jScrollPane1.setViewportView(aulas_tab);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 720, 360));

        aasignar_bot.setText("Asignar Equipo");
        aasignar_bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aasignar_botActionPerformed(evt);
            }
        });
        jPanel3.add(aasignar_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, 140, 40));

        agregarAu_bot.setText("+ Agregar Aula");
        agregarAu_bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAu_botActionPerformed(evt);
            }
        });
        jPanel3.add(agregarAu_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 160, 40));

        agregarCa_bot.setText("+ Agregar Categoria");
        agregarCa_bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCa_botActionPerformed(evt);
            }
        });
        jPanel3.add(agregarCa_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 180, 40));

        agregarEq_bot.setText("+ Agregar Equipo");
        agregarEq_bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEq_botActionPerformed(evt);
            }
        });
        jPanel3.add(agregarEq_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 160, 40));

        amodificar_bot.setText("Modificar");
        amodificar_bot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amodificar_botActionPerformed(evt);
            }
        });
        jPanel3.add(amodificar_bot, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 140, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 1070, 610));

        jPanel2.setBackground(new java.awt.Color(162, 3, 136));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LAB_nom.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        LAB_nom.setForeground(new java.awt.Color(254, 254, 254));
        LAB_nom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/g12280.png"))); // NOI18N
        LAB_nom.setText("Director General: Fulanito de Tal");
        jPanel2.add(LAB_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 46, 461, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white_logo.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 110));

        jPanel1.setBackground(new java.awt.Color(56, 56, 56));
        jPanel1.setMaximumSize(new java.awt.Dimension(210, 610));
        jPanel1.setMinimumSize(new java.awt.Dimension(210, 610));
        jPanel1.setPreferredSize(new java.awt.Dimension(210, 610));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("____________________________________");
        jLabel4.setPreferredSize(new java.awt.Dimension(210, 17));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 230, -1));

        BTN_menu.setBackground(new java.awt.Color(30, 30, 30));
        BTN_menu.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        BTN_menu.setForeground(new java.awt.Color(254, 254, 254));
        BTN_menu.setText("MENÚ");
        BTN_menu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BTN_menu.setBorderPainted(false);
        BTN_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BTN_menu.setFocusPainted(false);
        BTN_menu.setMaximumSize(new java.awt.Dimension(210, 60));
        BTN_menu.setMinimumSize(new java.awt.Dimension(210, 60));
        BTN_menu.setPreferredSize(new java.awt.Dimension(210, 60));
        BTN_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_menuActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 90));

        BTN_disponibilidad.setBackground(new java.awt.Color(30, 30, 30));
        BTN_disponibilidad.setForeground(new java.awt.Color(254, 254, 254));
        BTN_disponibilidad.setText("Disponibilidad");
        BTN_disponibilidad.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BTN_disponibilidad.setBorderPainted(false);
        BTN_disponibilidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BTN_disponibilidad.setFocusPainted(false);
        BTN_disponibilidad.setMaximumSize(new java.awt.Dimension(210, 60));
        BTN_disponibilidad.setMinimumSize(new java.awt.Dimension(210, 60));
        BTN_disponibilidad.setPreferredSize(new java.awt.Dimension(210, 60));
        BTN_disponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_disponibilidadActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_disponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 50));

        BTN_maestros.setBackground(new java.awt.Color(30, 30, 30));
        BTN_maestros.setForeground(new java.awt.Color(254, 254, 254));
        BTN_maestros.setText("Maestros");
        BTN_maestros.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BTN_maestros.setBorderPainted(false);
        BTN_maestros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BTN_maestros.setFocusPainted(false);
        BTN_maestros.setMaximumSize(new java.awt.Dimension(210, 60));
        BTN_maestros.setMinimumSize(new java.awt.Dimension(210, 60));
        BTN_maestros.setPreferredSize(new java.awt.Dimension(210, 60));
        BTN_maestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_maestrosActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_maestros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 210, 50));

        BTN_materias.setBackground(new java.awt.Color(30, 30, 30));
        BTN_materias.setForeground(new java.awt.Color(254, 254, 254));
        BTN_materias.setText("Materias");
        BTN_materias.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BTN_materias.setBorderPainted(false);
        BTN_materias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BTN_materias.setFocusPainted(false);
        BTN_materias.setMaximumSize(new java.awt.Dimension(210, 60));
        BTN_materias.setMinimumSize(new java.awt.Dimension(210, 60));
        BTN_materias.setPreferredSize(new java.awt.Dimension(210, 60));
        BTN_materias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_materiasActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_materias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 210, 50));

        BTN_carreras.setBackground(new java.awt.Color(30, 30, 30));
        BTN_carreras.setForeground(new java.awt.Color(254, 254, 254));
        BTN_carreras.setText("Carreras");
        BTN_carreras.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BTN_carreras.setBorderPainted(false);
        BTN_carreras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BTN_carreras.setFocusPainted(false);
        BTN_carreras.setMaximumSize(new java.awt.Dimension(210, 60));
        BTN_carreras.setMinimumSize(new java.awt.Dimension(210, 60));
        BTN_carreras.setPreferredSize(new java.awt.Dimension(210, 60));
        BTN_carreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_carrerasActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_carreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 210, 50));

        BTN_planes.setBackground(new java.awt.Color(30, 30, 30));
        BTN_planes.setForeground(new java.awt.Color(254, 254, 254));
        BTN_planes.setText("Planes de Estudio");
        BTN_planes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BTN_planes.setBorderPainted(false);
        BTN_planes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BTN_planes.setFocusPainted(false);
        BTN_planes.setMaximumSize(new java.awt.Dimension(210, 60));
        BTN_planes.setMinimumSize(new java.awt.Dimension(210, 60));
        BTN_planes.setPreferredSize(new java.awt.Dimension(210, 60));
        BTN_planes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_planesActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_planes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 210, 50));

        BTN_aulas.setBackground(new java.awt.Color(30, 30, 30));
        BTN_aulas.setForeground(new java.awt.Color(254, 254, 254));
        BTN_aulas.setText("Aulas");
        BTN_aulas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BTN_aulas.setBorderPainted(false);
        BTN_aulas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BTN_aulas.setFocusPainted(false);
        BTN_aulas.setMaximumSize(new java.awt.Dimension(210, 60));
        BTN_aulas.setMinimumSize(new java.awt.Dimension(210, 60));
        BTN_aulas.setPreferredSize(new java.awt.Dimension(210, 60));
        BTN_aulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_aulasActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_aulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 210, 50));

        BTN_grupo.setBackground(new java.awt.Color(30, 30, 30));
        BTN_grupo.setForeground(new java.awt.Color(254, 254, 254));
        BTN_grupo.setText("Grupos");
        BTN_grupo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BTN_grupo.setBorderPainted(false);
        BTN_grupo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BTN_grupo.setFocusPainted(false);
        BTN_grupo.setMaximumSize(new java.awt.Dimension(210, 60));
        BTN_grupo.setMinimumSize(new java.awt.Dimension(210, 60));
        BTN_grupo.setPreferredSize(new java.awt.Dimension(210, 60));
        BTN_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_grupoActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 210, 50));

        BTN_horario.setBackground(new java.awt.Color(30, 30, 30));
        BTN_horario.setForeground(new java.awt.Color(254, 254, 254));
        BTN_horario.setText("Horarios");
        BTN_horario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BTN_horario.setBorderPainted(false);
        BTN_horario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BTN_horario.setFocusPainted(false);
        BTN_horario.setMaximumSize(new java.awt.Dimension(210, 60));
        BTN_horario.setMinimumSize(new java.awt.Dimension(210, 60));
        BTN_horario.setPreferredSize(new java.awt.Dimension(210, 60));
        BTN_horario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_horarioActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 210, 50));

        BTN_puntos.setBackground(new java.awt.Color(30, 30, 30));
        BTN_puntos.setForeground(new java.awt.Color(254, 254, 254));
        BTN_puntos.setText("Puntos Confianza");
        BTN_puntos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        BTN_puntos.setBorderPainted(false);
        BTN_puntos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BTN_puntos.setFocusPainted(false);
        BTN_puntos.setMaximumSize(new java.awt.Dimension(210, 60));
        BTN_puntos.setMinimumSize(new java.awt.Dimension(210, 60));
        BTN_puntos.setPreferredSize(new java.awt.Dimension(210, 60));
        BTN_puntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_puntosActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 210, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 210, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aasignar_botActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aasignar_botActionPerformed
        int bandera = 0;
        for (int i = 0; i < 10; i++) {
            if(aulas_tab.isRowSelected(i)){
                consultar(ae_tab,"SELECT categorias_equipo.nombre, equipo.id, equipo.nombre, equipo.descripcion FROM equipo JOIN categorias_equipo WHERE equipo.id_categoria = categorias_equipo.id");
                int row = aulas_tab.getSelectedRow();
                String ae_aula = aulas_tab.getModel().getValueAt(row, 0).toString();
                setCantidades(ae_aula);
                
                agregarAu_pan.setVisible(false);
                agregarEq_pan.setVisible(false);
                agregarCa_pan.setVisible(false);
                modificarAu_pan.setVisible(false);
                
                ae_pan.setVisible(true);
                bandera = 1;
            }
        }
        if(bandera != 1)
            JOptionPane.showMessageDialog(this,"Seleccione el registro de la tabla ha asignar equipos.","Alerta",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aasignar_botActionPerformed

    private void agregarAu_botActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAu_botActionPerformed
        ae_pan.setVisible(false);
        agregarEq_pan.setVisible(false);
        agregarCa_pan.setVisible(false);
        modificarAu_pan.setVisible(false);
        
        agregarAu_pan.setVisible(true);
    }//GEN-LAST:event_agregarAu_botActionPerformed

    private void agregarEq_botActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEq_botActionPerformed
        agregarAu_pan.setVisible(false);
        ae_pan.setVisible(false);
        agregarCa_pan.setVisible(false);
        modificarAu_pan.setVisible(false);
        
        agregarEq_pan.setVisible(true);
    }//GEN-LAST:event_agregarEq_botActionPerformed

    private void agregarCa_botActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCa_botActionPerformed
        agregarAu_pan.setVisible(false);
        agregarEq_pan.setVisible(false);
        ae_pan.setVisible(false);
        modificarAu_pan.setVisible(false);
        
        agregarCa_pan.setVisible(true); 
    }//GEN-LAST:event_agregarCa_botActionPerformed

    private void amodificar_botActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amodificar_botActionPerformed
        int bandera = 0;
        for (int i = 0; i < 10; i++) {
            if(aulas_tab.isRowSelected(i)){
                agregarAu_pan.setVisible(false);
                agregarEq_pan.setVisible(false);
                agregarCa_pan.setVisible(false);
                ae_pan.setVisible(false);
                mostrarDatos();
                modificarAu_pan.setVisible(true);                        
                bandera = 1;
            }
        }
        if(bandera != 1)
            JOptionPane.showMessageDialog(rootPane,"  Alerta, Seleccione el registro de la tabla ha modificar.");
    }//GEN-LAST:event_amodificar_botActionPerformed

    private void acancelar_botActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acancelar_botActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "¿Desea salir de la ventana sin guardar?","Confirmar",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
        }else if (response == JOptionPane.YES_OPTION) {
            limpiarCasillas();
            agregarAu_pan.setVisible(false);
        }
    }//GEN-LAST:event_acancelar_botActionPerformed

    private void mcancelar_botActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcancelar_botActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "¿Desea salir de la ventana sin guardar?","Confirmar",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
        }else if (response == JOptionPane.YES_OPTION) {
            limpiarCasillas();
            modificarAu_pan.setVisible(false);        
        }
    }//GEN-LAST:event_mcancelar_botActionPerformed

    private void ccancelar_botActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccancelar_botActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "¿Desea salir de la ventana sin guardar?","Confirmar",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
        }else if (response == JOptionPane.YES_OPTION) {
            limpiarCasillas();
            agregarCa_pan.setVisible(false);        
        }
    }//GEN-LAST:event_ccancelar_botActionPerformed

    private void ecancelar_bot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecancelar_bot1ActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "¿Desea salir de la ventana sin guardar?","Confirmar",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
        }else if (response == JOptionPane.YES_OPTION) {
            limpiarCasillas();
            agregarEq_pan.setVisible(false);        
        }        
    }//GEN-LAST:event_ecancelar_bot1ActionPerformed

    private void mnombre_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnombre_txtKeyTyped
        val.validar(evt);
    }//GEN-LAST:event_mnombre_txtKeyTyped

    private void mguardar_botActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mguardar_botActionPerformed
        modificarAula();
    }//GEN-LAST:event_mguardar_botActionPerformed

    private void aguardar_botActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aguardar_botActionPerformed
        agregarAula();
    }//GEN-LAST:event_aguardar_botActionPerformed

    private void eguardar_bot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eguardar_bot1ActionPerformed
        agregarEquipo();
    }//GEN-LAST:event_eguardar_bot1ActionPerformed

    private void cguardar_botActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cguardar_botActionPerformed
        agregarCategoria();
    }//GEN-LAST:event_cguardar_botActionPerformed

    private void aeguardar_botActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aeguardar_botActionPerformed
    asignarEquipo();
    }//GEN-LAST:event_aeguardar_botActionPerformed

    private void cnombre_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnombre_txtKeyTyped
        val.validar(evt);
    }//GEN-LAST:event_cnombre_txtKeyTyped

    private void enombre_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enombre_txtKeyTyped
        val.validar(evt);
    }//GEN-LAST:event_enombre_txtKeyTyped

    private void anombre_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anombre_txtKeyTyped
        val.validar(evt);
    }//GEN-LAST:event_anombre_txtKeyTyped

    private void aecancelar_botActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aecancelar_botActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "¿Desea salir de la ventana sin guardar?","Confirmar",
        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.NO_OPTION) {
        }else if (response == JOptionPane.YES_OPTION) {
            limpiarCasillas();
            ae_pan.setVisible(false);        
        }
    }//GEN-LAST:event_aecancelar_botActionPerformed

    private void BTN_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_menuActionPerformed
        // TODO add your handling code here:
        Menu abrir = new Menu();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        abrir.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_BTN_menuActionPerformed

    private void BTN_disponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_disponibilidadActionPerformed
        // TODO add your handling code here:
        AdministrarDisponibilidad abrir = new AdministrarDisponibilidad();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        abrir.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_BTN_disponibilidadActionPerformed

    private void BTN_maestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_maestrosActionPerformed
        // TODO add your handling code here:
        AdministrarProfesores abrir = new AdministrarProfesores();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        abrir.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_BTN_maestrosActionPerformed

    private void BTN_materiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_materiasActionPerformed
        // TODO add your handling code here:
        AdministrarMaterias abrir = new AdministrarMaterias();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        abrir.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_BTN_materiasActionPerformed

    private void BTN_carrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_carrerasActionPerformed
        // TODO add your handling code here:
        AdministrarCarreras abrir = new AdministrarCarreras();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        abrir.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_BTN_carrerasActionPerformed

    private void BTN_planesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_planesActionPerformed
        // TODO add your handling code here:
        AdministrarPlanes abrir = new AdministrarPlanes();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        abrir.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_BTN_planesActionPerformed

    private void BTN_aulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_aulasActionPerformed
        // TODO add your handling code here:
        AdministrarAula abrir = new AdministrarAula();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        abrir.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_BTN_aulasActionPerformed

    private void BTN_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_grupoActionPerformed
        // TODO add your handling code here:
        AdministrarGrupos abrir = new AdministrarGrupos();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        abrir.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_BTN_grupoActionPerformed

    private void BTN_horarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_horarioActionPerformed
        // TODO add your handling code here:
        AdministrarHorarios abrir = new AdministrarHorarios();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        abrir.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_BTN_horarioActionPerformed

    private void BTN_puntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_puntosActionPerformed
        // TODO add your handling code here:
        AdministrarPuntosConfianza abrir = new AdministrarPuntosConfianza();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        abrir.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_BTN_puntosActionPerformed

    private void limpiarCasillas(){
        enombre_txt.setText("");
        edescripcion_txt.setText("");
        cnombre_txt.setText("");
        cdescripcion_txt.setText("");
        aclave_txt.setText("");
        anombre_txt.setText("");
        acapacidad_sp.setValue(0);
        mnombre_txt.setText("");
        mcapacidad_sp.setValue(0);    
    }
    
    private void obtenerCategorias(){
        try {
            ecategoria_cb1.removeAllItems();
            ResultSet rs = conn.conectar("SELECT id, nombre FROM categorias_equipo");
            while(rs.next()){
                ecategoria_cb1.addItem(Integer.toString(rs.getInt("id"))+" .- "+rs.getString("nombre"));
            }
            rs.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,ex.getMessage()+"  Alerta, No hay conexión.");
        } 
    }

    private void mostrarDatos(){
        int row = aulas_tab.getSelectedRow();
        String id_clave = aulas_tab.getModel().getValueAt(row, 0).toString();

        try {
            ResultSet rs = conn.conectar("SELECT nombre, tipo, capacidad FROM aulas WHERE id = '"+ id_clave+"'");
            while(rs.next()){
                mnombre_txt.setText(rs.getString("nombre"));
                mtipo_cb.setSelectedItem(rs.getString("tipo"));
                mcapacidad_sp.setValue(rs.getInt("capacidad"));
            }
            rs.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,ex.getMessage()+"  Alerta, No hay conexión.");
        } 
    }

    private void setCantidades(String id_aa){
        try {
            ResultSet rs = conn.conectar("SELECT cantidad FROM aula_equipo WHERE id_aula = '"+id_aa+"'");
            int i = 0;
            while(rs.next()){
                String valor = rs.getString("cantidad");
                ae_tab.setValueAt(valor,i,4);
                i++;
            }
       } catch (Exception ex) {}        
    }
    
    private void obtenerID(int tab){
        try {
            String consulta="";
            if(tab==1){
                consulta="SELECT MAX(id) FROM categorias_equipo";
            }else if(tab==3){
                consulta="SELECT MAX(id_equipo) FROM aula_equipo";
            }else if(tab==4){
                consulta="SELECT MAX(id) FROM equipo";
            }
            ResultSet rs = conn.conectar(consulta);
            while(rs.next())
            {
                id=rs.getString(1);
            }
        } catch (Exception ex) {}
        
        
        int num = 0;
        
        try{
            num =Integer.parseInt(id);
        }catch(Exception e){
            num = 1;
        }
        num++;
        id=Integer.toString(num);
    }

    private void modificarAula() {
        int column = 0;
        int row = aulas_tab.getSelectedRow();
        String id_aula = aulas_tab.getModel().getValueAt(row, column).toString();

        String mtipo = (String)mtipo_cb.getSelectedItem();
        Integer mmyint = (Integer) mcapacidad_sp.getValue();
        String mcapacidad = mmyint.toString();
        int aint = Integer.parseInt(mcapacidad);
        if(mnombre_txt.getText().equals("")){           
            JOptionPane.showMessageDialog(this,"No dejar espacios en blanco.","Alerta",JOptionPane.INFORMATION_MESSAGE);
        }else{            
            try {
                if(!mnombre_txt.getText().equals(""))
                conn.insert("UPDATE aulas set nombre = '" + mnombre_txt.getText() + "' WHERE id = '"+id_aula+"'");
                if(!mtipo.equals(""))
                conn.insert("UPDATE aulas set tipo = '" + mtipo + "' WHERE id = '"+id_aula+"'");
                if(!mcapacidad.equals(""))
                conn.insert("UPDATE aulas set capacidad = " + aint + " WHERE id = '"+id_aula+"'");

                JOptionPane.showMessageDialog(this,"Se ha modificado exitosamente.","Aviso",JOptionPane.INFORMATION_MESSAGE);
                modificarAu_pan.setVisible(false);
                limpiarCasillas();
                consultar(aulas_tab,"SELECT * FROM aulas");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,"Intente de nuevo.","Error",JOptionPane.INFORMATION_MESSAGE);
            }
        }//else equals
    }

    private void agregarCategoria() {
        if(cnombre_txt.getText().equals("")||cdescripcion_txt.getText().equals("")){           
            JOptionPane.showMessageDialog(this,"No dejar espacios en blanco.","Alerta",JOptionPane.INFORMATION_MESSAGE);
        }else{
            obtenerID(1);
            aux=val.validarID(1,id);
            if(aux==false){
                try {
                    conn.insert("INSERT INTO categorias_equipo (id, nombre,descripcion) VALUES "
                    + "("+id+",'"+cnombre_txt.getText()+"','"+cdescripcion_txt.getText()+"')");
                    JOptionPane.showMessageDialog(this,"Se ha registrado exitosamente.\n ID: "+id,"Aviso",JOptionPane.INFORMATION_MESSAGE);
                    agregarCa_pan.setVisible(false);
                    limpiarCasillas();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this,"Intente de nuevo.","Error",JOptionPane.INFORMATION_MESSAGE);
                }
            }//if true
        }//else equals
    }
    
    private void agregarAula() {
        String atipo = (String)atipo_cb.getSelectedItem();
        Integer myint = (Integer) acapacidad_sp.getValue();
        String acapacidad = myint.toString();
        if(aclave_txt.getText().equals("")||anombre_txt.getText().equals("")||atipo.equals("")||acapacidad.equals("")){           
            JOptionPane.showMessageDialog(this,"No dejar espacios en blanco.","Alerta",JOptionPane.INFORMATION_MESSAGE);
        }else{
            aux=val.validarID(2,aclave_txt.getText());
            int aint = Integer.parseInt(acapacidad);
            if(aux==false){
                try {
                    conn.insert("INSERT INTO aulas (id, nombre, tipo, capacidad) VALUES "
                    + "('"+aclave_txt.getText()+"','"+anombre_txt.getText()+"','"+atipo+"',"+aint+")");
                    JOptionPane.showMessageDialog(this,"Se ha registrado exitosamente.\n ID: "+aclave_txt.getText(),"Aviso",JOptionPane.INFORMATION_MESSAGE);
                    agregarAu_pan.setVisible(false);
                    limpiarCasillas();
                    consultar(aulas_tab,"SELECT * FROM aulas");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this,"Intente de nuevo.","Error",JOptionPane.INFORMATION_MESSAGE);
                }
            }//if true
        }//else equals
    }
    
    private void asignarEquipo(){
        int row = aulas_tab.getSelectedRow();
        String ae_id_aula = aulas_tab.getModel().getValueAt(row, 0).toString();
        for (int i = 0; i < ae_tab.getRowCount(); i++){
            String ae_id_equipo = ae_tab.getModel().getValueAt(i, 1).toString();
            String ae_cantidad = "0";
            
            try{
                ae_cantidad = ae_tab.getModel().getValueAt(i, 4).toString();
            }catch(NullPointerException e){                
                ae_cantidad="0";
            }
            

            try {
                conn.insert("UPDATE aula_equipo SET cantidad = "+ae_cantidad+" WHERE id_equipo = "+ae_id_equipo+" AND id_aula = '"+ae_id_aula+"'");
                conn.insert("INSERT INTO aula_equipo (id_equipo, id_aula, cantidad) VALUES("+ae_id_equipo+",'"+ae_id_aula+"',"+ae_cantidad+")");
            } catch (Exception ex) {
                try {
                    conn.insert("INSERT INTO aula_equipo (id_equipo, id_aula, cantidad) VALUES("+ae_id_equipo+",'"+ae_id_aula+"',"+ae_cantidad+")");
                } catch (Exception ex1) {
                    
                }
            }
        }// for
        ae_pan.setVisible(false);
        limpiarCasillas();
        JOptionPane.showMessageDialog(this,"Se ha actualizado el registro.","Aviso",JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void agregarEquipo() {
        String ecat = (String)ecategoria_cb1.getSelectedItem();
        ecat = ecat.substring(0,1);
        obtenerID(4);
        if(enombre_txt.getText().equals("")||edescripcion_txt.getText().equals("")||ecat.equals("")){           
            JOptionPane.showMessageDialog(this,"No dejar espacios en blanco.","Alerta",JOptionPane.INFORMATION_MESSAGE);
        }else{
            aux=val.validarID(4,id);
            if(aux==false){
                try {
                    conn.insert("INSERT INTO equipo (id, nombre, descripcion, id_categoria) VALUES "
                    + "("+id+",'"+enombre_txt.getText()+"','"+edescripcion_txt.getText()+"','"+ecat+"')");
                    JOptionPane.showMessageDialog(this,"Se ha registrado exitosamente.\n ID: "+id,"Aviso",JOptionPane.INFORMATION_MESSAGE);
                    agregarEq_pan.setVisible(false);
                    limpiarCasillas();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this,"Intente de nuevo.","Error",JOptionPane.INFORMATION_MESSAGE);
                }
            }//if true
        }//else equals
    }
    
    public void consultar(JTable tablaObj, String sentencia){ 
        ResultSetMetaData rsm;
        DefaultTableModel dtm;
        try{
            limpiarTabla(tablaObj);
            ResultSet rs = null;
            rs=conn.conectar(sentencia);
            rsm=rs.getMetaData();
            ArrayList<Object[]> data = new ArrayList<>();
            while(rs.next()){
                Object[] rows = new Object[rsm.getColumnCount()];
                for(int i=0;i<rows.length;i++){
                    rows[i]=rs.getObject(i+1);
                }
                for(int v=0;v<data.size();v++){
                    data.remove(v);
                }
                data.add(rows);
                dtm=(DefaultTableModel)tablaObj.getModel();
                for(int j=0;j<data.size();j++){
                    dtm.addRow(data.get(j));
                }
            }
        }catch(SQLException e){}
    }

    private void limpiarTabla(JTable tabla){
        DefaultTableModel dtm;
        dtm=(DefaultTableModel)tabla.getModel();
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrarAula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_aulas;
    private javax.swing.JButton BTN_carreras;
    private javax.swing.JButton BTN_disponibilidad;
    private javax.swing.JButton BTN_grupo;
    private javax.swing.JButton BTN_horario;
    private javax.swing.JButton BTN_maestros;
    private javax.swing.JButton BTN_materias;
    private javax.swing.JButton BTN_menu;
    private javax.swing.JButton BTN_planes;
    private javax.swing.JButton BTN_puntos;
    private javax.swing.JLabel LAB_nom;
    private javax.swing.JButton aasignar_bot;
    private javax.swing.JButton acancelar_bot;
    private javax.swing.JSpinner acapacidad_sp;
    private javax.swing.JTextField aclave_txt;
    private javax.swing.JPanel ae_pan;
    private javax.swing.JTable ae_tab;
    private javax.swing.JButton aecancelar_bot;
    private javax.swing.JButton aeguardar_bot;
    private javax.swing.JButton agregarAu_bot;
    private javax.swing.JPanel agregarAu_pan;
    private javax.swing.JButton agregarCa_bot;
    private javax.swing.JPanel agregarCa_pan;
    private javax.swing.JButton agregarEq_bot;
    private javax.swing.JPanel agregarEq_pan;
    private javax.swing.JButton aguardar_bot;
    private javax.swing.JButton amodificar_bot;
    private javax.swing.JTextField anombre_txt;
    private javax.swing.JComboBox<String> atipo_cb;
    private javax.swing.JTable aulas_tab;
    private javax.swing.JButton ccancelar_bot;
    private javax.swing.JTextArea cdescripcion_txt;
    private javax.swing.JButton cguardar_bot;
    private javax.swing.JTextField cnombre_txt;
    private javax.swing.JButton ecancelar_bot1;
    private javax.swing.JComboBox<String> ecategoria_cb1;
    private javax.swing.JTextArea edescripcion_txt;
    private javax.swing.JButton eguardar_bot1;
    private javax.swing.JTextField enombre_txt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton mcancelar_bot;
    private javax.swing.JSpinner mcapacidad_sp;
    private javax.swing.JButton mguardar_bot;
    private javax.swing.JTextField mnombre_txt;
    private javax.swing.JPanel modificarAu_pan;
    private javax.swing.JComboBox<String> mtipo_cb;
    // End of variables declaration//GEN-END:variables
}
