/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import Control.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author margaroth
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
        TF_usu.setText("corozcog@upv.edu.mx");
        TF_con.setText("*2567782B7E56052F2703593E9DC0CAC796271A90");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TF_usu = new javax.swing.JTextField();
        TF_con = new javax.swing.JPasswordField();
        btn_ini = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 147, 90, 30));

        jLabel3.setText("Contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 100, 20));

        TF_usu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_usuActionPerformed(evt);
            }
        });
        jPanel1.add(TF_usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 200, -1));
        jPanel1.add(TF_con, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 200, -1));

        btn_ini.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btn_ini.setMnemonic('i');
        btn_ini.setText("Ingresar");
        btn_ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 112, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("Sistema de creacion de horarios de la UPV");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 450, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/upvfinal.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 979, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_usuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_usuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_usuActionPerformed

    private void btn_iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniActionPerformed
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_btn_iniActionPerformed

    
    //Todo codigo aqui
    ProyectoFinal p = new ProyectoFinal();
    
    
    public void validar(){
        String usuario,contra;
        usuario=TF_usu.getText();
        contra=TF_con.getText();
        int entrar=0;
        String persona = "";
        try{
        connection con = new connection();
        ResultSet rs = con.conectar("SELECT clv_usuario,pass_usuario,tipo_usuario,idcarrera FROM usuarios");
        while (rs.next()) {
            String user = rs.getString("clv_usuario");
            String cont = rs.getString("pass_usuario");
            String tipo = rs.getString("tipo_usuario");
            String carrera = rs.getString("idcarrera");
            if(usuario.equals(user)&&contra.equals(cont)){
                entrar = 1;
                if(tipo.equals("ADMI")){
                    tipo = "Administrador";
                }else if (tipo.equals("DIRE")){
                    tipo = "Director";
                }else{
                    tipo = "Profesor";
                }
                SharedData.setTipoUsuario(tipo);
                SharedData.setClave(user);
                SharedData.setCarrera(carrera);
            }
        }
        if (entrar == 1){
            Menu abrir = new Menu();
            abrir.setVisible(true);
            abrir.setLocationRelativeTo(null);
            abrir.setResizable(false);
            dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Ingrese datos correctos","Error",JOptionPane.INFORMATION_MESSAGE);

        }
        con.desconectar();
        }catch(SQLException ex){
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TF_con;
    private javax.swing.JTextField TF_usu;
    private javax.swing.JButton btn_ini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
